[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "node-rs-bcrypt"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
blowfish = {version = "0.7", features = ["bcrypt"]}
byteorder = "1"
napi = "1.0.0"
napi-derive = "1"
phf = {version = "0.8", features = ["macros"]}
radix64 = "0.6"
rand = "0.8"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[target.'cfg(windows)'.dependencies]
mimalloc = {version = "0.1"}

[dev-dependencies]
quickcheck = "1.0"

[build-dependencies]
napi-build = "1"
