[package]
name = "node-rs-jieba"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
jieba-rs = { version = "0.5", features = ["default-dict", "tfidf", "textrank"] }
napi-rs = { version = "0.3" }
napi-rs-derive = { version = "0.2" }
once_cell = "1.3"

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.3", features = ["disable_initial_exec_tls"] }

[build-dependencies]
napi-build = { version = "0.1" }