[package]
name = "argon2"
version = "0.1.0"
authors = ["LongYinan <longyinan.brooklyn@bytedance.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-rs = { version = "0.3" }
napi-rs-derive = { version = "0.2" }
rust-argon2  = "0.8"

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.3", features = ["disable_initial_exec_tls"] }

[build-dependencies]
napi-build = { version = "0.1" }